<$DSRC/mkfile-$CONF
TARG=libmemdraw.$L

OFILES=\
	alloc.$O\
	arc.$O\
	cload.$O\
	cmap.$O\
	cread.$O\
	defont.$O\
	draw.$O\
	ellipse.$O\
	fillpoly.$O\
	hwdraw.$O\
	line.$O\
	load.$O\
	openmemsubfont.$O\
	poly.$O\
	read.$O\
	string.$O\
	subfont.$O\
	unload.$O\
	write.$O

HFILE=\

<$DSRC/mklib-$CONF
