<$DSRC/mkfile-$CONF
TARG=libmemlayer.$L

OFILES=\
	draw.$O\
	lalloc.$O\
	layerop.$O\
	ldelete.$O\
	lhide.$O\
	line.$O\
	load.$O\
	lorigin.$O\
	lsetrefresh.$O\
	ltofront.$O\
	ltorear.$O\
	unload.$O\

HFILES=\
	../include/memlayer.h\
	../include/memdraw.h\
	../include/draw.h

<$DSRC/mklib-$CONF
