name: C

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7
    - name: install dependencies
      run: sudo apt-get update && sudo apt-get install -y libx11-dev libxt-dev
    - name: make clean
      run: CONF=unix make clean
    - name: make
      run: CONF=unix make
